### PR TITLE
Fix failing tests on PHP 8.4 (follow-up to mezzio-swoole#137)

### LINKED ISSUE #140: HttpServerFactory fails with swoole 6: Swoole\Runtime::enableCoroutine(): Argument #1 ($flags) must be of type int, true given
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.10.0

#### Summary

After upgrading to swoole 6.0.1 with php 8.4, this error is shown when trying to run services with coroutines enabled:

```
app-1      | [2025-02-14T15:34:27.287024+00:00] licensing-services-error.ERROR: Uncaught Exception TypeError: "Swoole\Runtime::enableCoroutine(): Argument #1 ($flags) must be of type int, true given" at /var/www/vendor/mezzio/mezzio-swoole/src/HttpServerFactory.php line 114 {"exception":"[object] (TypeError(code: 0): Swoole\\Runtime::enableCoroutine(): Argument #1 ($flags) must be of type int, true given at /var/www/vendor/mezzio/mezzio-swoole/src/HttpServerFactory.php:114)"} {"hostname":"9f91bcc4648d","service_id":"service"}
app-1      | 
app-1      | In HttpServerFactory.php line 114:
app-1      |                                                                                
app-1      |   Swoole\Runtime::enableCoroutine(): Argument #1 ($flags) must be of type int  
app-1      |   , true given                                                                 
app-1      |                                                                                
app-1      | 
app-1      | mezzio:swoole:start [-d|--daemonize] [-w|--num-workers NUM-WORKERS] [-t|--num-task-workers NUM-TASK-WORKERS]
```

`src/HttpServerFactory.php` has `SwooleRuntime::enableCoroutine(true);` (https://github.com/mezzio/mezzio-swoole/blob/4.11.x/src/HttpServerFactory.php#L114), after changing to `SwooleRuntime::enableCoroutine(1);` it works.

#### Current behavior

Server fails to start

#### How to reproduce

Update to swoole 6

#### Expected behavior

Server running

### PR DESCRIPTION
**Pull request by mairo744**
This PR addresses the test failures that occurred in [mezzio-swoole#137](https://github.com/mezzio/mezzio-swoole/pull/137), which introduced updates for PHP 8.4 compatibility.

### Summary of Changes

- Fixed issue with installing `inotify` on PHP 8.4
- Cleaned up doc
- Used Reflection to set readonly properties, addressing changes in object mutability in PHP 8.4

### Checklist

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Notes

Targeting `master` as this is a bugfix/QA cleanup directly related to ensuring stability on PHP 8.4.

> See original PR for context: https://github.com/mezzio/mezzio-swoole/pull/137

---

### CODE REVIEW

**Comment by mairo744** [comment]
Hi @gsteel, sorry to bother you — I just wanted to check if you might know who could review this PR, or point me in the right direction. I'd really appreciate any help. Thanks in advance!

File: test/SwooleRequestHandlerRunnerTest.php [hunk 1]
```diff
@@ -78,7 +80,13 @@ public function testConstructorRaisesExceptionWhenManagerPidIsNotZero(): void
 
     public function testRunRegistersExpectedHttpServerListenersAndStartsServerWhenInBaseMode(): void
     {
-        $this->httpServer->mode = SWOOLE_BASE;
+        if (PHP_VERSION_ID >= 80300) {
+            $reflection = new ReflectionProperty($this->httpServer, 'mode');
+            /** @psalm-suppress UnusedMethodCall */
+            $reflection->setAccessible(true);
```
Comment (gsteel) [inline test/SwooleRequestHandlerRunnerTest.php]: This is unnecessary since 8.1
https://www.php.net/manual/en/reflectionproperty.setaccessible.php

File: test/SwooleRequestHandlerRunnerTest.php [hunk 2]
```diff
@@ -104,7 +112,14 @@ public function testRunRegistersExpectedHttpServerListenersAndStartsServerWhenIn
...
     public function testRunRegistersExpectedHttpServerListenersAndStartsServerWhenInProcessMode(): void
     {
-        $this->httpServer->mode = SWOOLE_PROCESS;
+        if (PHP_VERSION_ID >= 80200 && PHP_VERSION_ID < 80300) {
+            $this->markTestSkipped('Test relies on modifying readonly properties, which is not allowed in PHP 8.2+');
+        }
+
+        $reflection = new ReflectionProperty($this->httpServer, 'mode');
+        /** @psalm-suppress UnusedMethodCall */
+        $reflection->setAccessible(true);
```
Comment (gsteel) [inline test/SwooleRequestHandlerRunnerTest.php]: This is unnecessary since 8.1
https://www.php.net/manual/en/reflectionproperty.setaccessible.php

**Review by gsteel — APPROVED** [review]
This looks good to me @mairo744 - Thanks!

Asking for other reviews because it's been a long time since I looked at this lib.

**Review by gsteel — CHANGES_REQUESTED** [review]
Please can you rebase onto 4.11.x - this patch adds support for 8.4 so it's a feature release.

File: test/SwooleRequestHandlerRunnerTest.php (hunk 1 above)
Comment (mairo744) [reply test/SwooleRequestHandlerRunnerTest.php]: Thank you, I wasn't aware of that

**Comment by mairo744** [comment]
Thanks @gsteel . I’ve updated the target branch to 4.11.x. Since 4.10.x and 4.11.x are currently identical, there’s nothing to rebase.
image

**Review by gsteel — APPROVED** [review]
🚢 !
