### PR TITLE
Fix remote address resolution when the app is served behind a reverse proxy

### LINKED ISSUE #9: Access logger does not log correct remote addresses when serving behind a proxy or load balancer
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.6.3 (probably any version since the access logger exists)

#### Summary

I have a mezzio app using mezzio-swoole, which is hosted behind a nginx configured as a reverse proxy.

I have configured the access logger like this:

```php
return [
    
    'mezzio-swoole' => [
        'swoole-http-server' => [
            'logger' => [
                'format' => '%h %l %u "%r" %>s %b',
            ],
        ],
    ],

];
```

However, I have noticed that the `%h` part is being replaced by the proxy IP address, instead of the real client address.

I have digged in the code and it looks like it's always using the `REMOTE_ADDR` server param, when it should be first checking the `HTTP_X_FORWARDED_FOR` one, and if not found, then fall back to `REMOTE_ADDR` (I think).

It should potentially check `HTTP_X_REAL_IP` and `HTTP_CLIENT_IP` first too, as those are common ways to forward real IP addresses from reverse proxies.

#### Current behavior

When using the `%h` or `%a` modifiers for the access logging format, if the app is served behind a reverse proxy, the proxy IP address is logged.

#### How to reproduce

Set up a mezzio skeleton app, install swoole and mezzio-swoole and add the logger config provided above.

Then put a reverse proxy in front of the app and try accessing it.

#### Expected behavior

When using the `%h` or `%a` modifiers for the access logging format, if the app is served behind a reverse proxy, the real client IP address is logged.

---

I can provide a fix for this if you think that would be proper solution.

### PR DESCRIPTION
**Pull request by acelaya**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This improves how the client IP address is detected when using the `%h` and/or `%a` modifiers for access logs.

Now also the `x-real-ip`, `client-ip` and `x-forwarded-for` headers are taken into consideration, in that order, in case the app is being served behind a load balancer, reverse proxy or CDN.

This closes #9

### CODE REVIEW

File: src/Log/AccessLogDataMap.php [hunk 1]
```diff
@@ -94,7 +95,12 @@ public static function createWithStaticResource(
      */
     public function getClientIp() : string
     {
-        return $this->getLocalIp();
+        $headers = ['x-forwarded-for', 'client-ip', 'x-real-ip'];
+        $headerValue = array_reduce($headers, function (?string $default, string $header) {
+            return $this->request->header[$header] ?? $default;
+        });
```
Comment (acelaya) [inline src/Log/AccessLogDataMap.php:101]: I was initially planning to get this info from `request->server`, but I have run the app locally with a simple nginx proxy and it looks swoole does not mimic the behavior of `$_SERVER` 1 to 1.

The headers are there though, so this approach works.

File: src/Log/AccessLogDataMap.php [hunk 2]
```diff
@@ -94,7 +95,12 @@ public static function createWithStaticResource(
      */
     public function getClientIp() : string
     {
-        return $this->getLocalIp();
+        $headers = ['x-forwarded-for', 'client-ip', 'x-real-ip'];
+        $headerValue = array_reduce($headers, function (?string $default, string $header) {
```
Comment (samsonasik) [inline src/Log/AccessLogDataMap.php:99]: can use `static function`, eg:

```suggestion
        $headerValue = array_reduce($headers, static function (?string $default, string $header) {
```

Comment (michalbundyra) [reply src/Log/AccessLogDataMap.php:99]: Actually you cannot in that case. `$this` is used inside.

Comment (samsonasik) [reply src/Log/AccessLogDataMap.php:99]: @michalbundyra oh yeah, just realize that.

File: src/Log/AccessLogDataMap.php (hunk 1 above)
Comment (weierophinney) [reply src/Log/AccessLogDataMap.php:101]: Question: should we loop over all of these, or use only the first matched? (Current approach here loops over all, and uses last matched.)

Comment (acelaya) [reply src/Log/AccessLogDataMap.php:101]: Yeah, you are right. I guess I tried too hard to use a more functional approach when a simple foreach loop is probably more convenient here 😅

I'll change it.

Comment (weierophinney) [reply src/Log/AccessLogDataMap.php:101]: I get tripped up by that **all**. **the**. **time**. Love functional paradigms, and try to use them... but sometimes they actually are the wrong fit. (Particularly when performance is a consideration!)

Comment (acelaya) [reply src/Log/AccessLogDataMap.php]: Same here, haha.

Anyway, I have just pushed the change and used a loop with an early return instead.
