### PR TITLE
Expand compatibility to allow `psr/http-message:^2`

### LINKED ISSUE #120: 4.7.0 is not compatible with psr/http-messages:^2.0
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.7.0

#### Summary

Upgrading to 4.7.0 with `psr/http-message:^2.0` gives compatibility errors in `Mezzio\Swoole\SwooleStream`.

```
Fatal error: Declaration of Mezzio\Swoole\SwooleStream::close() must be compatible with Psr\Http\Message\StreamInterface::close(): void in /app/vendor/mezzio/mezzio-swoole/src/SwooleStream.php on line 242
```

### PR DESCRIPTION
**Pull request by Xerkus**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

#114 provided compatibility with psr http message v2 but missed `SwooleStream` which was not caught by tests since v2 was never pulled by composer in CI.

### CODE REVIEW

File: src/SwooleStream.php [hunk 1]
```diff
@@ -102,35 +96,25 @@ public function getSize()
...
     {
         return true;
     }
 
-    /**
-     * @param int $length
-     * @return string
-     */
-    public function read($length)
+    public function read(int $length): string
```
Comment (Ocramius) [inline src/SwooleStream.php:117]: We should probably not add parameter types, unless our lowest CI is checking for compatibility here

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: src/SwooleStream.php (hunk 1 above)
Comment (Xerkus) [reply src/SwooleStream.php:117]: Lowest does check compatibility with 1.1

Thankfully class is final so no inheritance BC to worry about here.

**Review by Ocramius — APPROVED** [review]
Thanks @Xerkus
